import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type InferGetServerSidePropsType } from "next";
import { api } from "~/utils/api";
import type { inferRouterInputs, inferRouterOutputs } from "@trpc/server";

import { useEffect, useRef } from "react";
import { AppRouter } from "~/server/api/root";
type ImageData = {
  rank: number;
  image: string;
  totalvoates: number;
};

type getImageOutput = inferRouterOutputs<AppRouter["images"]>;
const RankingTable = ({ data }: { data: ImageData[] }) => {
  return (
    <div className="flex w-screen space-x-4">
      {["Most expensive", "Most dangerous", "Most stylish"].map((i) => {
        return (
          <div
            key={i}
            className="flex w-1/3 flex-col items-center space-y-4 overflow-x-auto"
          >
            <h1 className="text-5xl font-bold">{i}</h1>
            <table className="table w-max">
              <thead>
                <tr>
                  <th>Rank</th>
                  <th>Image</th>
                  <th>Total votes</th>
                </tr>
              </thead>
              <tbody>
                {data?.map((img, index) => {
                  return (
                    <tr key={index}>
                      <td>{img.rank}</td>
                      <td>
                        <img
                          className="h-[10rem] w-[10rem] rounded-lg"
                          src={img.image}
                          alt="image"
                        />
                      </td>
                      <td>{img.totalvoates}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        );
      })}
    </div>
  );
};

const Rankings: NextPage = () => {
  const { data } = api.images.getImages.useQuery();
  const gradient =
    "bg-gradient-to-r from-purple-400 text-8xl to-pink-600 bg-clip-text  font-extrabold text-transparent";
  console.log(data);
  return (
    <>
      <Head>
        <title>AI Ranking pairs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center space-y-8">
        <div className={gradient}>AI GALLERY RANKING</div>
        {data ? <RankingTable data={data} /> : <div>loading</div>}
        <Link
          href="/"
          className=" rounded-md bg-blue-900 p-4 text-4xl font-bold"
        >
          Go Rank
        </Link>
      </main>
    </>
  );
};

export default Rankings;
