import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type InferGetServerSidePropsType } from "next";
import { api } from "~/utils/api";
import { db, ranktable } from "./db/drizzleDB";
import { type Art, type NewArt } from "./db/drizzleDB";
import { useEffect, useRef, useState } from "react";
import { TotalArt } from "./db/TotalArt";
import { createServerSideHelpers } from "@trpc/react-query/server";
import { appRouter } from "~/server/api/root";
import superjson from "superjson";
import Image from "next/image";
const Home: NextPage = () => {
  const [currentImages, setCurrent] = useState([]);
  const gradient =
    "bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text  font-extrabold text-transparent";
  const [refetchNum, setRefetchNum] = useState(6);
  const [index, setIndex] = useState(0);
  const [fadeIn, fadeOut] = useState(true);
  const reff = useRef(null);
  const submit = api.images.SubmitImageRank.useMutation();
  const [title, setTitle] = useState("most expensive");
  const { data, isLoading, refetch } = api.images.getImagePair.useQuery(
    {
      number: refetchNum,
    },
    {
      onSuccess(data) {
        if (index + 4 > currentImages.length) {
          setCurrent((curr) => [...curr, ...data]);
        }
      },
    }
  );

  const toggleAnimation = () => {
    fadeOut(false);
    console.log(reff);
  };

  const handleClick = async (img) => {
    submit.mutate({
      pickedImage: img.image,
      otherImage: currentImages[index + 1].image,
    });
    setTitle(
      ["most expensive", "most dangerous", "most stylish"][
        Math.floor(Math.random() * 3)
      ]
    );
    toggleAnimation();
    setIndex(index + 2);
    await refetch().then((newData) => {
      console.log(currentImages);
    });
    console.log(index);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-center">
        <div className="bg-gradient-to-r from-purple-400 to-pink-600 bg-clip-text pb-8 text-8xl font-extrabold text-transparent">
          AI GALLERY RANKING
        </div>

        <div className={` text-6xl font-bold`}>{title}:</div>

        <div className=" flex space-x-8 p-8">
          {/* {props.data.map((image) => {
            return (
              <div key={image.image} className="h-1/2 w-1/2">
                <img src={image.image} alt="something" />
              </div>
            );
          })}{" "} */}
          {currentImages.length > 0 ? (
            [currentImages[index], currentImages[index + 1]].map((img) => {
              return (
                <div
                  ref={reff}
                  key={img?.image}
                  className={`${
                    fadeIn ? "opacity-100" : "opacity-0"
                  } transition-opacity duration-500`}
                  onClick={() => {
                    handleClick(img);
                  }}
                >
                  <Image
                    onLoadingComplete={() => fadeOut(true)}
                    src={img?.image}
                    height={200}
                    quality={100}
                    width={200}
                    alt="something"
                    unoptimized
                    className="h-[50rem] w-[50rem] rounded-lg border-blue-200 hover:border-2"
                  />
                </div>
              );
            })
          ) : (
            <div>loading</div>
          )}
        </div>
        <Link href="/rankings" className=" rounded-md bg-blue-900 p-4 text-4xl">
          <div className={`font-bold`}>See Rankings</div>
        </Link>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: {},
    transformer: superjson, // optional - adds superjson serialization
  });
  const art = await db.select().from(ranktable);
  await helpers.images.getImagePair.prefetch({ number: 4 });
  return {
    props: {
      trpcState: helpers.dehydrate(),
    },
  };
}

export default Home;
